# Generated by Django 4.2.20 on 2025-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinquiry',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
