# Generated by Django 4.2.20 on 2025-05-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_coachreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachreview',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
