# Generated by Django 4.2.20 on 2025-06-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_rename_firs_name_coachreview_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='coach',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
