# Generated by Django 4.2.20 on 2025-06-03 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_rename_name_coach_first_name_coach_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile link')),
                ('facebook', models.URLField(blank=True, help_text='Facebook profile link')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile link')),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel link')),
                ('tiktok', models.URLField(blank=True, help_text='TikTok profile link')),
                ('x', models.URLField(blank=True, help_text='X (formerly Twitter) profile link')),
                ('trustpilot', models.URLField(blank=True, help_text='Trustpilot profile link')),
                ('google', models.URLField(blank=True, help_text='Google profile link')),
                ('provexpert', models.URLField(blank=True, help_text='ProvExpert profile link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='coach.coach')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
