# Generated by Django 4.2.20 on 2025-06-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='coach.category'),
        ),
        migrations.AddField(
            model_name='coach',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='coach.subcategory'),
        ),
    ]
