# Generated by Django 4.2.20 on 2025-06-22 08:23

import coach.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=coach.models.get_coach_media_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='coach.coach')),
            ],
        ),
    ]
