# Generated by Django 4.2.20 on 2025-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_coachmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='about',
            field=models.TextField(blank=True, help_text='A brief description about the coach.'),
        ),
    ]
