# Generated by Django 4.2.20 on 2025-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_alter_coach_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='about',
            field=models.TextField(blank=True, default='', help_text='A brief description about the coach.'),
        ),
    ]
