# Generated by Django 4.2.20 on 2025-06-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_alter_coach_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
