# Generated by Django 4.2.20 on 2025-06-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0014_coach_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='company',
            field=models.CharField(blank=True, default='', help_text='The company or organization the coach is associated with.', max_length=255),
        ),
    ]
