# Generated by Django 4.2.20 on 2025-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0015_coach_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='city',
            field=models.CharField(blank=True, default='', help_text="City of the coach's location.", max_length=255),
        ),
        migrations.AddField(
            model_name='coach',
            name='country',
            field=models.CharField(blank=True, default='', help_text="Country of the coach's location.", max_length=255),
        ),
        migrations.AddField(
            model_name='coach',
            name='street_no',
            field=models.CharField(blank=True, default='', help_text="Street number of the coach's location.", max_length=255),
        ),
        migrations.AddField(
            model_name='coach',
            name='zip_code',
            field=models.CharField(blank=True, default='', help_text="Zip code of the coach's location.", max_length=20),
        ),
        migrations.AlterField(
            model_name='coach',
            name='website',
            field=models.URLField(blank=True, help_text="Coach's personal or business website."),
        ),
    ]
