# Generated by Django 4.2.20 on 2025-06-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0016_coach_city_coach_country_coach_street_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='type',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('online_offline', 'Online and Offline')], default='online_offline', max_length=20),
        ),
    ]
