# Generated by Django 4.2.20 on 2025-06-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0017_alter_coach_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
