# Generated by Django 4.2.20 on 2025-06-24 16:12

import coach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0018_alter_coach_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, help_text='Icon for the category.', null=True, upload_to=coach.models.get_category_icon_upload_path),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.FileField(blank=True, help_text='Icon for the subcategory.', null=True, upload_to=coach.models.get_subcategory_icon_upload_path),
        ),
    ]
