# Generated by Django 4.2.20 on 2025-06-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0019_category_icon_subcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='review_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
