# Generated by Django 4.2.20 on 2025-07-05 14:52

import coach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0020_coach_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=coach.models.get_coach_cover_image_upload_path),
        ),
    ]
