# Generated by Django 4.2.20 on 2025-07-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=64)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('link_canonical', models.URLField(blank=True)),
                ('schema', models.TextField(blank=True)),
                ('site_map', models.TextField(blank=True)),
                ('web_page', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
