# Generated by Django 4.2.20 on 2025-04-04 07:18

import core.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.users.models.get_profile_picture_upload_location),
        ),
    ]
