# Generated by Django 4.2.20 on 2025-06-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='country_code',
        ),
    ]
