# Generated by Django 4.2.20 on 2025-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='description',
            field=models.TextField(default='', verbose_name='Field Description'),
        ),
    ]
