# Generated by Django 4.2.20 on 2025-06-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_fields_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Field Description'),
        ),
    ]
