# Generated by Django 4.2.20 on 2025-06-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_fields_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='coach_category',
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(default='', max_length=255, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fields',
            field=models.CharField(max_length=255, verbose_name='Fields'),
        ),
    ]
