# Generated by Django 4.2.20 on 2025-06-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_savedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Indicates if the product is featured'),
        ),
    ]
