# Generated by Django 4.2.20 on 2025-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producttype_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='language',
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian')], default='en', help_text='Language of the product', max_length=10),
        ),
    ]
