# Generated by Django 4.2.20 on 2025-07-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_producttype_language_product_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL for the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, help_text='The date when the product was released', null=True),
        ),
    ]
