# Generated by Django 4.2.20 on 2025-07-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_external_url_product_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ct_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the product in the Coach Trusted system', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the product', max_length=100, null=True, unique=True),
        ),
    ]
